# Generated by Django 5.2.16 on 2026-07-21 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('estimated_minutes', models.PositiveIntegerField(default=30, verbose_name='Длительность, минут')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_courses', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название')),
                ('lesson_type', models.CharField(choices=[('text', 'Текст'), ('video', 'Видео'), ('link', 'Ссылка'), ('file', 'Файл')], default='text', max_length=20, verbose_name='Тип')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('media_url', models.URLField(blank=True, verbose_name='Ссылка на материал')),
                ('duration_minutes', models.PositiveIntegerField(default=5, verbose_name='Длительность, минут')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.course')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('course', 'position'), name='unique_lesson_position')],
            },
        ),
    ]
