# Generated by Django 5.2.16 on 2026-07-21 18:33

import apps.learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, upload_to=apps.learning.models.lesson_video_path, verbose_name='Видеофайл'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Исходное имя видео'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Размер видео'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки видео'),
        ),
    ]
