# Generated by Django 5.2.16 on 2026-07-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_lesson_quiz"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект обучения",
                "verbose_name_plural": "Проекты обучения",
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="contentproject",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"),
                name="unique_learning_project_name_per_owner",
            ),
        ),
        migrations.CreateModel(
            name="ContentFolder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180, verbose_name="Название")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="learning.contentfolder",
                        verbose_name="Родительская папка",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="learning.contentproject",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Папка материалов",
                "verbose_name_plural": "Папки материалов",
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="learning.contentfolder",
                verbose_name="Папка",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="learning.contentproject",
                verbose_name="Проект",
            ),
        ),
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=220, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликована"), ("archived", "В архиве")],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_learning_paths",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_paths",
                        to="learning.contentfolder",
                        verbose_name="Папка",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_paths",
                        to="learning.contentproject",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Траектория",
                "verbose_name_plural": "Траектории",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningPathCourse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=0, verbose_name="Позиция")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_entries",
                        to="learning.course",
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_courses",
                        to="learning.learningpath",
                    ),
                ),
            ],
            options={"ordering": ["position", "id"]},
        ),
        migrations.AddField(
            model_name="learningpath",
            name="courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="learning_paths",
                through="learning.LearningPathCourse",
                to="learning.course",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningpathcourse",
            constraint=models.UniqueConstraint(
                fields=("learning_path", "course"),
                name="unique_course_in_learning_path",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningpathcourse",
            constraint=models.UniqueConstraint(
                fields=("learning_path", "position"),
                name="unique_learning_path_position",
            ),
        ),
    ]
