# Generated by Django 5.2.16 on 2026-07-29 18:03

import apps.learning.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_courseenrollment_lessonprogress_quizattempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.learning.models.question_image_path, verbose_name='Изображение')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Размер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_image_assets', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Изображение обучения',
                'verbose_name_plural': 'Изображения обучения',
                'ordering': ['-created_at'],
            },
        ),
    ]
