from django.contrib import admin

from .models import (
    AbsenceRequest,
    Competency,
    DailyTranscript,
    AuditEvent,
    Candidate,
    CandidateAssignment,
    CandidateComment,
    CandidateExperience,
    CandidateOffer,
    CandidateResume,
    CandidateStage,
    CandidateStageEvent,
    EmployeeDocument,
    EmployeeGoal,
    EmployeeLearning,
    EmployeeProfile,
    EmploymentEvent,
    Interview,
    InterviewFeedback,
    HrImportBatch,
    Position,
    StaffPosition,
    Vacancy,
    OnboardingPlan,
    OnboardingTemplate,
    PerformanceCycle,
    PerformanceReview,
    PerformanceScore,
    ProductUpdate,
)

admin.site.register([
    Position, StaffPosition, EmployeeProfile, EmployeeGoal, EmploymentEvent, EmployeeLearning,
    EmployeeDocument, AbsenceRequest, PerformanceCycle, Competency, PerformanceReview, PerformanceScore,
    DailyTranscript, ProductUpdate,
    OnboardingTemplate, OnboardingPlan, CandidateStage, Vacancy, Candidate, CandidateExperience,
    CandidateComment, CandidateStageEvent, CandidateAssignment, CandidateResume, CandidateOffer, AuditEvent,
    Interview, InterviewFeedback, HrImportBatch,
])
