from django.urls import path

from .views import (
    CandidateDetailView,
    CandidateListCreateView,
    CandidateStageListView,
    EmployeeDetailView,
    EmployeeDocumentListCreateView,
    EmployeeGoalDetailView,
    EmployeeGoalListCreateView,
    EmployeeLearningDetailView,
    EmployeeLearningListCreateView,
    EmployeeListCreateView,
    EmploymentEventListCreateView,
    HcmSummaryView,
    PositionListView,
    OrganizationDepartmentDetailView,
    OrganizationDepartmentListCreateView,
    StaffPositionDetailView,
    StaffPositionListCreateView,
    VacancyDetailView,
    VacancyListCreateView,
)

urlpatterns = [
    path("employees/", EmployeeListCreateView.as_view(), name="employees"),
    path("employees/<int:pk>/", EmployeeDetailView.as_view(), name="employee-detail"),
    path("employees/<int:employee_id>/goals/", EmployeeGoalListCreateView.as_view(), name="employee-goals"),
    path("employees/<int:employee_id>/history/", EmploymentEventListCreateView.as_view(), name="employee-history"),
    path("employees/<int:employee_id>/learning/", EmployeeLearningListCreateView.as_view(), name="employee-learning"),
    path("employees/<int:employee_id>/documents/", EmployeeDocumentListCreateView.as_view(), name="employee-documents"),
    path("employee-goals/<int:pk>/", EmployeeGoalDetailView.as_view(), name="employee-goal-detail"),
    path("employee-learning/<int:pk>/", EmployeeLearningDetailView.as_view(), name="employee-learning-detail"),
    path("positions/", PositionListView.as_view(), name="positions"),
    path("org/departments/", OrganizationDepartmentListCreateView.as_view(), name="organization-departments"),
    path("org/departments/<int:pk>/", OrganizationDepartmentDetailView.as_view(), name="organization-department-detail"),
    path("org/staff-positions/", StaffPositionListCreateView.as_view(), name="staff-positions"),
    path("org/staff-positions/<int:pk>/", StaffPositionDetailView.as_view(), name="staff-position-detail"),
    path("candidates/", CandidateListCreateView.as_view(), name="candidates"),
    path("candidates/<int:pk>/", CandidateDetailView.as_view(), name="candidate-detail"),
    path("candidate-stages/", CandidateStageListView.as_view(), name="candidate-stages"),
    path("vacancies/", VacancyListCreateView.as_view(), name="vacancies"),
    path("vacancies/<int:pk>/", VacancyDetailView.as_view(), name="vacancy-detail"),
    path("hcm/summary/", HcmSummaryView.as_view(), name="hcm-summary"),
]
