from django.urls import path

from .views import (
    AbsenceCancelView,
    AuditEventListView,
    AbsenceDecisionView,
    AbsenceDetailView,
    AbsenceListCreateView,
    CandidateDetailView,
    CandidateListCreateView,
    CandidateHireView,
    CandidateOfferApproveView,
    CandidateOfferDetailView,
    CandidateOfferListCreateView,
    CandidateOfferOutcomeView,
    CandidateOfferSubmitView,
    CandidateStageListView,
    EmployeeDetailView,
    EmployeeImportView,
    LearningImportView,
    DocumentArchiveView,
    DocumentDecisionView,
    DocumentDownloadView,
    DocumentListCreateView,
    DocumentSendView,
    DailyTranscriptDetailView,
    DailyTranscriptListCreateView,
    EmployeeDocumentListCreateView,
    EmployeeGoalDetailView,
    EmployeeGoalListCreateView,
    EmployeeLearningDetailView,
    EmployeeLearningListCreateView,
    EmployeeListCreateView,
    EmploymentEventListCreateView,
    HcmSummaryView,
    HcmDashboardView,
    InboxView,
    InterviewCompleteView,
    InterviewDetailView,
    InterviewFeedbackView,
    InterviewListCreateView,
    InterviewOptionsView,
    InterviewStartView,
    PositionListView,
    OrganizationDepartmentDetailView,
    OrganizationDepartmentListCreateView,
    StaffPositionDetailView,
    StaffPositionListCreateView,
    VacancyDetailView,
    VacancyListCreateView,
    EmployeeOnboardingView,
    OnboardingTemplateDetailView,
    OnboardingTemplateListCreateView,
    OnboardingOptionsView,
    CompetencyListCreateView,
    PerformanceCycleLaunchView,
    PerformanceCycleListCreateView,
    PerformanceManagerSubmitView,
    PerformanceReviewDetailView,
    PerformanceReviewListView,
    PerformanceSelfSubmitView,
    ProductUpdateApplyView,
    ProductUpdateDetailView,
    ProductUpdateListCreateView,
)

urlpatterns = [
    path("audit-events/", AuditEventListView.as_view(), name="audit-events"),
    path("product-updates/", ProductUpdateListCreateView.as_view(), name="product-updates"),
    path("product-updates/<int:pk>/", ProductUpdateDetailView.as_view(), name="product-update-detail"),
    path("product-updates/<int:pk>/apply/", ProductUpdateApplyView.as_view(), name="product-update-apply"),
    path("daily-transcripts/", DailyTranscriptListCreateView.as_view(), name="daily-transcripts"),
    path("daily-transcripts/<int:pk>/", DailyTranscriptDetailView.as_view(), name="daily-transcript-detail"),
    path("inbox/", InboxView.as_view(), name="inbox"),
    path("performance/competencies/", CompetencyListCreateView.as_view(), name="performance-competencies"),
    path("performance/cycles/", PerformanceCycleListCreateView.as_view(), name="performance-cycles"),
    path("performance/cycles/<int:pk>/launch/", PerformanceCycleLaunchView.as_view(), name="performance-cycle-launch"),
    path("performance/reviews/", PerformanceReviewListView.as_view(), name="performance-reviews"),
    path("performance/reviews/<int:pk>/", PerformanceReviewDetailView.as_view(), name="performance-review-detail"),
    path("performance/reviews/<int:pk>/self/", PerformanceSelfSubmitView.as_view(), name="performance-self-submit"),
    path("performance/reviews/<int:pk>/manager/", PerformanceManagerSubmitView.as_view(), name="performance-manager-submit"),
    path("documents/", DocumentListCreateView.as_view(), name="documents"),
    path("documents/<int:pk>/download/", DocumentDownloadView.as_view(), name="document-download"),
    path("documents/<int:pk>/send/", DocumentSendView.as_view(), name="document-send"),
    path("documents/<int:pk>/decision/", DocumentDecisionView.as_view(), name="document-decision"),
    path("documents/<int:pk>/archive/", DocumentArchiveView.as_view(), name="document-archive"),
    path("absences/", AbsenceListCreateView.as_view(), name="absences"),
    path("absences/<int:pk>/", AbsenceDetailView.as_view(), name="absence-detail"),
    path("absences/<int:pk>/decision/", AbsenceDecisionView.as_view(), name="absence-decision"),
    path("absences/<int:pk>/cancel/", AbsenceCancelView.as_view(), name="absence-cancel"),
    path("employees/", EmployeeListCreateView.as_view(), name="employees"),
    path("employees/import/", EmployeeImportView.as_view(), name="employee-import"),
    path("learning-imports/ispring/", LearningImportView.as_view(), name="learning-import-ispring"),
    path("employees/<int:pk>/", EmployeeDetailView.as_view(), name="employee-detail"),
    path("employees/<int:employee_id>/goals/", EmployeeGoalListCreateView.as_view(), name="employee-goals"),
    path("employees/<int:employee_id>/history/", EmploymentEventListCreateView.as_view(), name="employee-history"),
    path("employees/<int:employee_id>/learning/", EmployeeLearningListCreateView.as_view(), name="employee-learning"),
    path("employees/<int:employee_id>/documents/", EmployeeDocumentListCreateView.as_view(), name="employee-documents"),
    path("employees/<int:employee_id>/onboarding/", EmployeeOnboardingView.as_view(), name="employee-onboarding"),
    path("employee-goals/<int:pk>/", EmployeeGoalDetailView.as_view(), name="employee-goal-detail"),
    path("employee-learning/<int:pk>/", EmployeeLearningDetailView.as_view(), name="employee-learning-detail"),
    path("positions/", PositionListView.as_view(), name="positions"),
    path("org/departments/", OrganizationDepartmentListCreateView.as_view(), name="organization-departments"),
    path("org/departments/<int:pk>/", OrganizationDepartmentDetailView.as_view(), name="organization-department-detail"),
    path("org/staff-positions/", StaffPositionListCreateView.as_view(), name="staff-positions"),
    path("org/staff-positions/<int:pk>/", StaffPositionDetailView.as_view(), name="staff-position-detail"),
    path("candidates/", CandidateListCreateView.as_view(), name="candidates"),
    path("candidates/<int:pk>/", CandidateDetailView.as_view(), name="candidate-detail"),
    path("candidates/<int:pk>/hire/", CandidateHireView.as_view(), name="candidate-hire"),
    path("offers/", CandidateOfferListCreateView.as_view(), name="candidate-offers"),
    path("offers/<int:pk>/", CandidateOfferDetailView.as_view(), name="candidate-offer-detail"),
    path("offers/<int:pk>/submit/", CandidateOfferSubmitView.as_view(), name="candidate-offer-submit"),
    path("offers/<int:pk>/approve/", CandidateOfferApproveView.as_view(), name="candidate-offer-approve"),
    path("offers/<int:pk>/outcome/", CandidateOfferOutcomeView.as_view(), name="candidate-offer-outcome"),
    path("candidate-stages/", CandidateStageListView.as_view(), name="candidate-stages"),
    path("interviews/", InterviewListCreateView.as_view(), name="interviews"),
    path("interviews/options/", InterviewOptionsView.as_view(), name="interview-options"),
    path("interviews/<int:pk>/", InterviewDetailView.as_view(), name="interview-detail"),
    path("interviews/<int:pk>/start/", InterviewStartView.as_view(), name="interview-start"),
    path("interviews/<int:pk>/feedback/", InterviewFeedbackView.as_view(), name="interview-feedback"),
    path("interviews/<int:pk>/complete/", InterviewCompleteView.as_view(), name="interview-complete"),
    path("vacancies/", VacancyListCreateView.as_view(), name="vacancies"),
    path("vacancies/<int:pk>/", VacancyDetailView.as_view(), name="vacancy-detail"),
    path("onboarding-templates/", OnboardingTemplateListCreateView.as_view(), name="onboarding-templates"),
    path("onboarding-templates/<int:pk>/", OnboardingTemplateDetailView.as_view(), name="onboarding-template-detail"),
    path("onboarding-options/", OnboardingOptionsView.as_view(), name="onboarding-options"),
    path("hcm/summary/", HcmSummaryView.as_view(), name="hcm-summary"),
    path("hcm/dashboard/", HcmDashboardView.as_view(), name="hcm-dashboard"),
]
