# Generated by Django 5.2.16 on 2026-07-28 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_user_role_hr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Этап')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_terminal', models.BooleanField(default=False, verbose_name='Финальный')),
            ],
            options={
                'verbose_name': 'Этап подбора',
                'verbose_name_plural': 'Этапы подбора',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=80)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=240, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('desired_position', models.CharField(max_length=180, verbose_name='Позиция')),
                ('desired_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ожидания по зарплате')),
                ('skills', models.TextField(blank=True, verbose_name='Навыки')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='Источник')),
                ('next_action_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующее действие')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='identity.department')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiting_candidates', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='people.candidatestage')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=40, unique=True, verbose_name='Табельный номер')),
                ('grade', models.CharField(blank=True, max_length=80, verbose_name='Грейд')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('education', models.CharField(blank=True, max_length=240, verbose_name='Образование')),
                ('competencies', models.TextField(blank=True, verbose_name='Компетенции')),
                ('status', models.CharField(choices=[('employed', 'Работает'), ('probation', 'Испытательный срок'), ('dismissed', 'Уволен')], default='employed', max_length=20, verbose_name='Статус')),
                ('checklist_score', models.PositiveSmallIntegerField(default=0, verbose_name='Чек-лист, %')),
                ('development_progress', models.PositiveSmallIntegerField(default=0, verbose_name='План развития, %')),
                ('salary_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Оклад')),
                ('monthly_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Месячная премия')),
                ('quarterly_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Квартальная премия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='people.position')),
            ],
            options={
                'verbose_name': 'Карточка сотрудника',
                'verbose_name_plural': 'Карточки сотрудников',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
