# Generated by Django 5.2.16 on 2026-07-28 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_content_library'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Документ')),
                ('document_type', models.CharField(blank=True, max_length=120, verbose_name='Тип')),
                ('number', models.CharField(blank=True, max_length=120, verbose_name='Номер')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='people.employeeprofile')),
            ],
            options={
                'verbose_name': 'Документ сотрудника',
                'verbose_name_plural': 'Документы сотрудников',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Цель')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс, %')),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('in_progress', 'В работе'), ('completed', 'Выполнена')], default='planned', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='people.employeeprofile')),
            ],
            options={
                'verbose_name': 'Цель развития',
                'verbose_name_plural': 'Цели развития',
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('hired', 'Приём'), ('transfer', 'Перевод'), ('promotion', 'Повышение'), ('review', 'Оценка'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=220, verbose_name='Событие')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('effective_date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employment_events', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_events', to='people.employeeprofile')),
            ],
            options={
                'verbose_name': 'Кадровое событие',
                'verbose_name_plural': 'Кадровые события',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Назначен'), ('in_progress', 'Проходит'), ('completed', 'Завершён')], default='assigned', max_length=20, verbose_name='Статус')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс, %')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Результат, %')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='learning.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_assignments', to='people.employeeprofile')),
            ],
            options={
                'verbose_name': 'Назначение обучения',
                'verbose_name_plural': 'Назначения обучения',
                'ordering': ['status', '-assigned_at'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'course'), name='unique_employee_course_assignment')],
            },
        ),
    ]
