# Generated by Django 5.2.16 on 2026-07-28 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_department_manager_department_parent'),
        ('people', '0002_employeedocument_employeegoal_employmentevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headcount', models.PositiveIntegerField(default=1, verbose_name='Штатных единиц')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_positions', to='identity.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_positions', to='people.position')),
            ],
            options={
                'verbose_name': 'Штатная позиция',
                'verbose_name_plural': 'Штатные позиции',
                'ordering': ['department__name', 'position__name'],
                'constraints': [models.UniqueConstraint(fields=('department', 'position'), name='unique_department_staff_position')],
            },
        ),
    ]
