# Generated by Django 5.2.16 on 2026-07-28 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_vacancy_candidate_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='hired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оформлен'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hired_employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_candidate', to='people.employeeprofile', verbose_name='Оформленный сотрудник'),
        ),
    ]
