# Generated by Django 5.2.16 on 2026-07-28 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_department_manager_department_parent'),
        ('learning', '0006_content_library'),
        ('people', '0005_candidate_hired_at_candidate_hired_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название')),
                ('duration_days', models.PositiveSmallIntegerField(default=30, verbose_name='Срок адаптации, дней')),
                ('checklist', models.JSONField(blank=True, default=list, verbose_name='Чек-лист')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_templates', to='identity.department')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_templates', to='learning.learningpath')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_templates', to='people.position')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Шаблон онбординга',
                'verbose_name_plural': 'Шаблоны онбординга',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.JSONField(blank=True, default=list, verbose_name='Чек-лист')),
                ('status', models.CharField(choices=[('active', 'В процессе'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('due_date', models.DateField(verbose_name='Плановое завершение')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_plans', to='people.employeeprofile')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_plans', to='learning.learningpath')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_onboarding_plans', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='people.onboardingtemplate')),
            ],
            options={
                'verbose_name': 'План онбординга',
                'verbose_name_plural': 'Планы онбординга',
                'ordering': ['-created_at'],
            },
        ),
    ]
