# Generated by Django 5.2.16 on 2026-07-28 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_onboardingtemplate_onboardingplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_type', models.CharField(choices=[('vacation', 'Отпуск'), ('sick', 'Больничный'), ('remote', 'Удалённая работа'), ('unpaid', 'За свой счёт'), ('other', 'Другое')], max_length=20, verbose_name='Тип отсутствия')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('decision_note', models.TextField(blank=True, verbose_name='Комментарий согласующего')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_requests', to='people.employeeprofile')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_absence_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на отсутствие',
                'verbose_name_plural': 'Заявки на отсутствие',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
