# Generated by Django 5.2.16 on 2026-07-28 18:19

import apps.people.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_absencerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='decision_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий сотрудника'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(blank=True, upload_to=apps.people.models.employee_document_path, verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='file_original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='file_sha256',
            field=models.CharField(blank=True, max_length=64, verbose_name='Контрольная сумма'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Размер файла'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='requires_signature',
            field=models.BooleanField(default=False, verbose_name='Требует подтверждения'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлен'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждён'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('awaiting', 'Ожидает подтверждения'), ('signed', 'Подтверждён'), ('declined', 'Отклонён'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_employee_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
