# Generated by Django 5.2.16 on 2026-07-28 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_employeedocument_decision_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Компетенция')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Идёт оценка'), ('completed', 'Завершён')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Цикл оценки',
                'verbose_name_plural': 'Циклы оценки',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('self', 'Ожидает самооценки'), ('manager', 'Ожидает руководителя'), ('completed', 'Завершена')], default='self', max_length=20, verbose_name='Статус')),
                ('self_summary', models.TextField(blank=True, verbose_name='Итоги сотрудника')),
                ('manager_summary', models.TextField(blank=True, verbose_name='Итоги руководителя')),
                ('development_plan', models.TextField(blank=True, verbose_name='План развития')),
                ('self_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Самооценка завершена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='people.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='people.employeeprofile')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка сотрудника',
                'verbose_name_plural': 'Оценки сотрудников',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Самооценка')),
                ('manager_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка руководителя')),
                ('self_comment', models.TextField(blank=True, verbose_name='Комментарий сотрудника')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий руководителя')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='people.competency')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='people.performancereview')),
            ],
            options={
                'verbose_name': 'Оценка компетенции',
                'verbose_name_plural': 'Оценки компетенций',
                'ordering': ['competency__category', 'competency__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='performancereview',
            constraint=models.UniqueConstraint(fields=('cycle', 'employee'), name='unique_cycle_employee_review'),
        ),
        migrations.AddConstraint(
            model_name='performancescore',
            constraint=models.UniqueConstraint(fields=('review', 'competency'), name='unique_review_competency'),
        ),
    ]
