# Generated by Django 5.2.16 on 2026-07-28 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_department_manager_department_parent'),
        ('people', '0009_competency_performancecycle_performancereview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название')),
                ('meeting_date', models.DateField(verbose_name='Дата дэйлика')),
                ('source', models.CharField(choices=[('paste', 'Вставлен текст'), ('file', 'Загружен файл'), ('api', 'Получено по API')], default='paste', max_length=20, verbose_name='Источник')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('raw_text', models.TextField(verbose_name='Расшифровка')),
                ('analysis', models.JSONField(blank=True, default=dict, verbose_name='Результат анализа')),
                ('coverage_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Покрытие курсами, %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_transcripts', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_transcripts', to='identity.department')),
            ],
            options={
                'verbose_name': 'Расшифровка дэйлика',
                'verbose_name_plural': 'Расшифровки дэйликов',
                'ordering': ['-meeting_date', '-created_at'],
            },
        ),
    ]
