# Generated by Django 5.2.16 on 2026-07-28 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_dailytranscript'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название обновления')),
                ('description', models.TextField(verbose_name='Описание изменения')),
                ('effective_date', models.DateField(verbose_name='Дата вступления в силу')),
                ('status', models.CharField(choices=[('analyzed', 'Готово к проверке'), ('applied', 'Применено')], default='analyzed', max_length=20, verbose_name='Статус')),
                ('analysis', models.JSONField(blank=True, default=dict, verbose_name='Затронутые материалы')),
                ('applied_targets', models.JSONField(blank=True, default=list, verbose_name='Обновлённые материалы')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Применено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обновление продукта',
                'verbose_name_plural': 'Обновления продукта',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
