# Generated by Django 5.2.16 on 2026-07-28 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_productupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название')),
                ('scheduled_at', models.DateTimeField(verbose_name='Дата и время')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='Продолжительность, минут')),
                ('format', models.CharField(choices=[('online', 'Онлайн'), ('office', 'В офисе'), ('phone', 'Телефон')], default='online', max_length=20, verbose_name='Формат')),
                ('location', models.CharField(blank=True, max_length=240, verbose_name='Место')),
                ('meeting_url', models.URLField(blank=True, verbose_name='Ссылка на встречу')),
                ('questions', models.JSONField(default=list, verbose_name='Сценарий вопросов')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('in_progress', 'Проводится'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('decision', models.CharField(choices=[('pending', 'Решение не принято'), ('advance', 'Перевести дальше'), ('hold', 'Резерв'), ('reject', 'Отказать')], default='pending', max_length=20, verbose_name='Решение')),
                ('summary', models.TextField(blank=True, verbose_name='Итоговый комментарий')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='people.candidate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='assigned_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Собеседование',
                'verbose_name_plural': 'Собеседования',
                'ordering': ['scheduled_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=list, verbose_name='Оценки по вопросам')),
                ('overall_score', models.PositiveSmallIntegerField(verbose_name='Общая оценка')),
                ('recommendation', models.CharField(choices=[('advance', 'Рекомендую дальше'), ('hold', 'Нужна дополнительная оценка'), ('reject', 'Не рекомендую')], max_length=20, verbose_name='Рекомендация')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='people.interview')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка собеседования',
                'verbose_name_plural': 'Оценки собеседований',
                'ordering': ['submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('interview', 'participant'), name='unique_interview_feedback_participant')],
            },
        ),
    ]
