# Generated by Django 5.2.16 on 2026-07-28

import apps.people.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0012_interview_interviewfeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position_title", models.CharField(max_length=180, verbose_name="Должность")),
                ("salary", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Оклад")),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="Плановая дата выхода")),
                ("valid_until", models.DateField(blank=True, null=True, verbose_name="Действует до")),
                ("probation_months", models.PositiveSmallIntegerField(default=3, verbose_name="Испытательный срок, месяцев")),
                ("work_format", models.CharField(choices=[("office", "Офис"), ("hybrid", "Гибрид"), ("remote", "Удалённо")], default="office", max_length=20, verbose_name="Формат работы")),
                ("conditions", models.TextField(blank=True, verbose_name="Условия")),
                ("file", models.FileField(blank=True, upload_to=apps.people.models.candidate_offer_path, verbose_name="Файл оффера")),
                ("file_original_name", models.CharField(blank=True, max_length=255, verbose_name="Исходное имя файла")),
                ("status", models.CharField(choices=[("draft", "Черновик"), ("pending", "На согласовании"), ("approved", "Согласован"), ("accepted", "Принят кандидатом"), ("declined", "Отклонён кандидатом"), ("withdrawn", "Отозван")], default="draft", max_length=20, verbose_name="Статус")),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Согласован")),
                ("responded_at", models.DateTimeField(blank=True, null=True, verbose_name="Ответ кандидата")),
                ("decision_comment", models.TextField(blank=True, verbose_name="Комментарий к решению")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_candidate_offers", to=settings.AUTH_USER_MODEL)),
                ("candidate", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="offers", to="people.candidate")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_candidate_offers", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Оффер кандидату",
                "verbose_name_plural": "Офферы кандидатам",
                "ordering": ["-created_at"],
            },
        ),
    ]
